version: '3'
services:
  webserver:
    build: ./webserver
    volumes:
     - ./webserver:/var/www/html
  node-api1:
    build: ./node-API

  node-api2:
    build: ./node-API

  node-api3:
    build: ./node-API
  proxy:
    image: 'nginx:latest'
    ports:
     - "80:80"
    volumes:
     - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-api1
      - node-api2
      - node-api3
      - webserver



